/*
    02 - MIT044IP - Gatilhos
*/
user function zIniNmFo()
    local aArea := FWGetArea()
    local nRet := ""

    if ! INCLUI
        if SF1->F1_TIPO != "B" .and. SF1->F1_TIPO != "D"
            nRet := posicione('SA2', 1, FwXFilial('SA2')+SF1->F1_FORNECE+SF1->F1_LOJA, 'A2_NOME')
        else
            nRet := posicione('SA1', 1, FwXFilial('SA1')+SF1->F1_FORNECE+SF1->F1_LOJA, 'A1_NOME')
        endif
    endif
    FWRestArea(aArea)
return nRet
