/*
    01 - MIT044IP - Consulta Títulos a Pagar
*/
user function MTA103MNU()
    local aArea as array 
    
    aArea := FWGetArea()

    if ExistBlock("zMit01a()")
        u_zMit01a()
    endif

    /*
    If ExistBlock("F183TXIR")
        nTxAux    := ExecBlock( "F183TXIR", .F., .F., { nTaxaIrf } )

        If ValType(nTxAux) == "N"
            nTaxaIrf := If(nTxAux >= 0 , nTxAux, nTaxaIrf )
            nTxAux    := 0
        EndIf
    EndIf
    */

	FWRestArea(aArea)
return
